export enum Permissoes {
  cadastrarEditarCliente = '1',
  excluirCliente = '2',
  visualizarCliente = '3',
  cadastrarEditarPerfil = '4',
  visualizarPerfil = '5',
  excluirPerfil = '6',
  cadastrarEditarUsuario = '7',
  visualizarUsuario = '8',
  excluirUsuario = '9',
  cadastrarPendencia = '10',
  visualizarPendencia = '11',
  excluirPendencia = '12',
  finalizarPendencia = '13',
  cadastrarEditarAgenda = '14',
  cancelarAgenda = '15',
  finalizarAgenda = '16',
  visualizarAgenda = '17',
  excluirAgenda = '18'
}